
public class Find_the_difference {

	public static void main(String[] args) {
		/**
		 * Given two strings s and t which consist of only lowercase letters.

			String t is generated by random shuffling string s and then add one more letter at a random position.

			Find the letter that was added in t.
		 */
		//Input:
		//s = "abcd"
		//		t = "abced"
		//Output: 'e'

	}
	
    public char findTheDifference(String s, String t) {
    	//异或的定义就是相同为0， 不同为1；
    	//两个string只差一个字符，也就是说如果将两个string挨个异或，最后留下的只有那个后加的char
    		char result = t.charAt(t.length() - 1);
    		
    		for(int i = 0; i < s.length(); i++) {
    			result ^= s.charAt(i);
    			result ^= t.charAt(i);
    		}
    		return result;
    }

}
